"""
Consolidate Statistik-RA annual workbooks into normalized output tables.

Reads the canonical workbook for each year (as defined in source_manifest.csv),
routes it to the correct era-specific parser, and writes normalized CSVs to
output/data/.

Usage:
    python code/consolidate_ra.py [--era LABEL] [--year YEAR]

Optional filters:
    --era   one of: phase1_legacy | phase2_transition | phase3_modern
    --year  a four-digit year (must be canonical)

Outputs (output/data/):
    source_manifest.csv          generated by build_manifest.py (must exist first)
    canton_risk_group.csv        Phase 2/3: one row per year × canton × age × sex × hosp
    switzerland_summary.csv      Phase 3:   one row per year × age × sex × hosp × PCG
    schema_profile.csv           one row per canonical sheet sampled, with column headers

Dependencies: openpyxl, pandas (pip install openpyxl pandas)
"""

import argparse
import csv
import os
import sys

import openpyxl
import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE_DIR = os.path.join(ROOT, "data", "statistik-ra")
OUTPUT_DIR = os.path.join(ROOT, "output", "data")
MANIFEST_PATH = os.path.join(OUTPUT_DIR, "source_manifest.csv")


# ── provenance helper ─────────────────────────────────────────────────────────

def _stamp(df: pd.DataFrame, source_file: str, source_sheet: str, year: int, revision: int) -> pd.DataFrame:
    """Add provenance columns to a normalized dataframe."""
    df = df.copy()
    # Rename any existing columns that would collide with stamp columns
    stamp_cols = {"year", "revision", "source_file", "source_sheet"}
    conflicts = {c: f"data_{c}" for c in df.columns if c in stamp_cols}
    if conflicts:
        df = df.rename(columns=conflicts)
    df.insert(0, "year", year)
    df.insert(1, "revision", revision)
    df.insert(2, "source_file", source_file)
    df.insert(3, "source_sheet", source_sheet)
    return df


# ── era parsers ───────────────────────────────────────────────────────────────

def parse_phase2_canton_risk_group(wb: openpyxl.Workbook, filename: str, year: int, revision: int) -> pd.DataFrame | None:
    """
    Parse Phase 2 workbooks (2012–2019).

    Expected sheet: 'Daten YYYY'
    Expected schema (rows 4–5 are headers, data from row 6):
        Kanton | Geburtsjahre_von | Geburtsjahre_bis | Alter | Geschlecht | Aufenthalt | Monate | Kosten_CHF

    Returns a long-format dataframe with one row per
    canton × age_band × sex × prior_hospitalisation.
    """
    target_sheet = None
    for name in wb.sheetnames:
        if name.lower().startswith("daten"):
            target_sheet = name
            break

    if not target_sheet:
        print(f"  SKIP {filename}: no 'Daten' sheet found (sheets: {wb.sheetnames})")
        return None

    ws = wb[target_sheet]
    rows = list(ws.iter_rows(values_only=True))

    # Find the header row: look for a row containing 'Kanton' (case-insensitive)
    header_row_idx = None
    for i, row in enumerate(rows):
        if any(isinstance(c, str) and "kanton" in c.lower() for c in row):
            header_row_idx = i
            break

    if header_row_idx is None:
        print(f"  SKIP {filename}/{target_sheet}: could not locate header row")
        return None

    # Some years have a two-row header (row with col names + row with sub-labels).
    # Flatten by taking the first non-empty value per column across header rows.
    header_rows = rows[header_row_idx: header_row_idx + 2]
    headers = []
    for col_idx in range(len(header_rows[0])):
        val = None
        for hr in header_rows:
            v = hr[col_idx]
            if v is not None and str(v).strip():
                val = str(v).strip()
                break
        headers.append(val or f"col_{col_idx}")

    data_start = header_row_idx + 2
    data_rows = [r for r in rows[data_start:] if any(c is not None for c in r)]

    df = pd.DataFrame(data_rows, columns=headers[: len(data_rows[0])])

    # Deduplicate column names (merged/split headers can produce collisions)
    seen: dict[str, int] = {}
    deduped = []
    for c in df.columns:
        if c in seen:
            seen[c] += 1
            deduped.append(f"{c}_{seen[c]}")
        else:
            seen[c] = 0
            deduped.append(c)
    df.columns = deduped

    # Normalize column names to stable English identifiers
    rename_map = {}
    for col in df.columns:
        lc = col.lower()
        if "kanton" in lc:
            rename_map[col] = "canton"
        elif "von" in lc and "jahr" in lc.replace(" ", ""):
            rename_map[col] = "birth_year_from"
        elif "bis" in lc:
            rename_map[col] = "birth_year_to"
        elif "alter" in lc:
            rename_map[col] = "age_band"
        elif "geschlecht" in lc:
            rename_map[col] = "sex"
        elif "aufenthalt" in lc:
            rename_map[col] = "prior_hospitalisation"
        elif "monat" in lc:
            rename_map[col] = "insured_months"
        elif "arzneimittelkosten" in lc:
            rename_map[col] = "drug_cost_flag"
        elif "kosten" in lc and "arzneimittel" not in lc and "beteiligung" not in lc:
            rename_map[col] = "total_cost_chf"
        elif "kostenbeteiligung" in lc:
            rename_map[col] = "cost_sharing_chf"
    df = df.rename(columns=rename_map)

    # Drop rows where canton is missing (totals / blank separators)
    if "canton" in df.columns:
        df = df[df["canton"].notna() & (df["canton"].astype(str).str.strip() != "")]

    # Coerce numerics (squeeze DataFrame to Series if duplicate cols slipped through)
    for col in ["insured_months", "total_cost_chf"]:
        if col in df.columns:
            series = df[col]
            if isinstance(series, pd.DataFrame):
                series = series.iloc[:, 0]
            df[col] = pd.to_numeric(series, errors="coerce")

    return _stamp(df, filename, target_sheet, year, revision)


def parse_phase3_switzerland_summary(wb: openpyxl.Workbook, filename: str, year: int, revision: int) -> pd.DataFrame | None:
    """
    Parse Phase 3 Switzerland summary sheet (2020+).

    Looks for a sheet named 'YYYY - Schweiz' that contains the national
    aggregated risk-cell table including PCG columns.

    Returns a long-format dataframe with one row per
    age_band × sex × prior_hospitalisation × pcg_group.
    """
    # Find sheet matching 'YYYY - Schweiz' pattern for the target year
    target_sheet = None
    for name in wb.sheetnames:
        if "schweiz" in name.lower() and str(year) in name:
            target_sheet = name
            break
    # Fallback: any 'Schweiz' sheet
    if not target_sheet:
        for name in wb.sheetnames:
            if "schweiz" in name.lower():
                target_sheet = name
                break

    if not target_sheet:
        print(f"  SKIP {filename}: no 'Schweiz' sheet found (sheets: {wb.sheetnames})")
        return None

    ws = wb[target_sheet]
    # Use max_column from the worksheet to avoid row-length clipping in read_only mode
    max_col = ws.max_column or 1
    rows = list(ws.iter_rows(values_only=True, min_col=1, max_col=max_col))

    if not rows:
        print(f"  SKIP {filename}/{target_sheet}: empty sheet")
        return None

    # Row 0 is header in modern format
    raw_headers = [str(c).strip() if c is not None else f"col_{i}" for i, c in enumerate(rows[0])]
    data_rows = [r for r in rows[1:] if any(c is not None for c in r)]

    df = pd.DataFrame(data_rows, columns=raw_headers[: len(data_rows[0])] if data_rows else raw_headers)

    # Deduplicate column names (PCG-wide sheets often repeat short labels)
    seen_ch: dict[str, int] = {}
    deduped_ch = []
    for c in df.columns:
        if c in seen_ch:
            seen_ch[c] += 1
            deduped_ch.append(f"{c}_{seen_ch[c]}")
        else:
            seen_ch[c] = 0
            deduped_ch.append(c)
    df.columns = deduped_ch

    # Detect and rename fixed dimension columns.
    # The overall metric columns (Monate YYYY, Kosten YYYY CHF, Kobe YYYY CHF)
    # contain the reference year in their header text.  PCG-group columns
    # (e.g. "ABH \nMonate", "DM1\nKosten") do NOT — so we guard on year_str to
    # avoid collapsing all 22 PCG metrics into the same generic name.
    year_str = str(year)
    rename_map = {}
    for col in df.columns:
        lc = col.lower()
        if "altersklasse" in lc or "alters" in lc:
            rename_map[col] = "age_band"
        elif "geschlecht" in lc:
            rename_map[col] = "sex"
        elif "aufenthalt" in lc:
            rename_map[col] = "prior_hospitalisation"
        elif "monat" in lc and "keine" not in lc and year_str in col:
            rename_map[col] = "insured_months"
        elif "kosten" in lc and "keine" not in lc and "kobe" not in lc and year_str in col:
            rename_map[col] = "total_cost_chf"
        elif "kobe" in lc and "keine" not in lc and year_str in col:
            rename_map[col] = "cost_after_ra_chf"

    df = df.rename(columns=rename_map)

    # Coerce numerics (squeeze DataFrame to Series if duplicate cols slipped through)
    for col in df.columns:
        if col not in ("age_band", "sex", "prior_hospitalisation", "source_file", "source_sheet"):
            series = df[col]
            if isinstance(series, pd.DataFrame):
                series = series.iloc[:, 0]
            df[col] = pd.to_numeric(series, errors="coerce")

    return _stamp(df, filename, target_sheet, year, revision)


def parse_phase3_canton_risk_group(wb: openpyxl.Workbook, filename: str, year: int, revision: int) -> pd.DataFrame | None:
    """
    Parse Phase 3 Kanton und Risikogruppe sheet (2020+).

    Looks for a sheet named 'YYYY - Kanton und Risikogruppe'.
    Returns a long-format dataframe with one row per year × canton × risk-group.
    """
    target_sheet = None
    for name in wb.sheetnames:
        if "kanton" in name.lower() and "risikogruppe" in name.lower() and str(year) in name:
            target_sheet = name
            break
    if not target_sheet:
        for name in wb.sheetnames:
            if "kanton" in name.lower() and "risikogruppe" in name.lower():
                target_sheet = name
                break

    if not target_sheet:
        return None

    ws = wb[target_sheet]
    rows = list(ws.iter_rows(values_only=True))
    if not rows:
        return None

    headers_rg = [str(c).strip() if c is not None else f"col_{i}" for i, c in enumerate(rows[0])]
    data_rows = [r for r in rows[1:] if any(c is not None for c in r)]
    df = pd.DataFrame(data_rows, columns=headers_rg[: len(data_rows[0])] if data_rows else headers_rg)

    # Deduplicate column names
    seen_rg: dict[str, int] = {}
    deduped_rg = []
    for c in df.columns:
        if c in seen_rg:
            seen_rg[c] += 1
            deduped_rg.append(f"{c}_{seen_rg[c]}")
        else:
            seen_rg[c] = 0
            deduped_rg.append(c)
    df.columns = deduped_rg

    # Rename common columns
    rename_map = {}
    for col in df.columns:
        lc = col.lower()
        if "kanton" in lc:
            rename_map[col] = "canton"
        elif "risikogruppe" in lc or "risk" in lc:
            rename_map[col] = "risk_group"
        elif "monat" in lc:
            rename_map[col] = "insured_months"
        elif "kosten" in lc and "kobe" not in lc:
            rename_map[col] = "total_cost_chf"
        elif "kobe" in lc:
            rename_map[col] = "cost_after_ra_chf"
        elif "beitrag" in lc or "zahlung" in lc:
            rename_map[col] = "ra_payment_chf"
    df = df.rename(columns=rename_map)

    for col in df.columns:
        if col not in ("canton", "risk_group", "source_file", "source_sheet"):
            series = df[col]
            if isinstance(series, pd.DataFrame):
                series = series.iloc[:, 0]
            df[col] = pd.to_numeric(series, errors="coerce")

    return _stamp(df, filename, target_sheet, year, revision)


# ── schema profiler ───────────────────────────────────────────────────────────

def profile_workbook(filename: str, year: int, era: str) -> list[dict]:
    """
    Return one record per sheet with column headers and dimensions.
    Used to build schema_profile.csv.
    """
    path = os.path.join(SOURCE_DIR, filename)
    records = []
    try:
        wb = openpyxl.load_workbook(path, read_only=True, data_only=True)
        for sheet_name in wb.sheetnames:
            ws = wb[sheet_name]
            rows = list(ws.iter_rows(values_only=True, max_row=6))
            headers = []
            if rows:
                # Concatenate first two rows for multi-line headers
                for col_idx in range(len(rows[0])):
                    parts = []
                    for row in rows[:2]:
                        if col_idx < len(row) and row[col_idx] is not None:
                            parts.append(str(row[col_idx]).strip())
                    header = " / ".join(dict.fromkeys(parts)) if parts else ""
                    headers.append(header)

            n_rows = ws.max_row or 0
            n_cols = ws.max_column or 0
            records.append(
                {
                    "filename": filename,
                    "year": year,
                    "era": era,
                    "sheet": sheet_name,
                    "n_rows": n_rows,
                    "n_cols": n_cols,
                    "col_headers": " | ".join(headers[:12]),  # first 12 columns
                }
            )
        wb.close()
    except Exception as exc:
        records.append(
            {
                "filename": filename,
                "year": year,
                "era": era,
                "sheet": "ERROR",
                "n_rows": 0,
                "n_cols": 0,
                "col_headers": str(exc),
            }
        )
    return records


# ── main ──────────────────────────────────────────────────────────────────────

def load_manifest() -> list[dict]:
    if not os.path.exists(MANIFEST_PATH):
        sys.exit(
            f"Manifest not found at {MANIFEST_PATH}.\n"
            "Run:  python code/build_manifest.py  first."
        )
    with open(MANIFEST_PATH, newline="", encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--era", help="Process only this era (phase1_legacy | phase2_transition | phase3_modern)")
    parser.add_argument("--year", type=int, help="Process only this year")
    args = parser.parse_args()

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    manifest = load_manifest()

    canonical = [r for r in manifest if r["is_canonical"] == "True"]
    if args.era:
        canonical = [r for r in canonical if r["era"] == args.era]
    if args.year:
        canonical = [r for r in canonical if int(r["year"]) == args.year]

    print(f"Processing {len(canonical)} canonical workbook(s) …\n")

    all_canton = []
    all_ch_summary = []
    schema_profile = []

    for rec in canonical:
        fname = rec["filename"]
        year = int(rec["year"])
        revision = int(rec["revision"])
        era = rec["era"]
        path = os.path.join(SOURCE_DIR, fname)

        print(f"  {fname}  ({era})")

        # Profile sheet headers for every canonical workbook
        schema_profile.extend(profile_workbook(fname, year, era))

        try:
            wb = openpyxl.load_workbook(path, read_only=True, data_only=True)
        except Exception as exc:
            print(f"    ERROR opening workbook: {exc}")
            continue

        if era == "phase2_transition":
            df = parse_phase2_canton_risk_group(wb, fname, year, revision)
            if df is not None:
                all_canton.append(df)
                print(f"    canton_risk_group: {len(df)} rows")

        elif era == "phase3_modern":
            df_ch = parse_phase3_switzerland_summary(wb, fname, year, revision)
            if df_ch is not None:
                all_ch_summary.append(df_ch)
                print(f"    switzerland_summary: {len(df_ch)} rows")

            df_canton = parse_phase3_canton_risk_group(wb, fname, year, revision)
            if df_canton is not None:
                all_canton.append(df_canton)
                print(f"    canton_risk_group: {len(df_canton)} rows")

        else:
            print(f"    SKIP: phase1_legacy parsers not yet implemented (wide pivoted format requires manual schema mapping)")

        wb.close()

    # ── write outputs ─────────────────────────────────────────────────────────

    if schema_profile:
        profile_path = os.path.join(OUTPUT_DIR, "schema_profile.csv")
        pd.DataFrame(schema_profile).to_csv(profile_path, index=False)
        print(f"\nSchema profile -> {profile_path}  ({len(schema_profile)} sheets)")

    if all_canton:
        # Drop any remaining duplicate columns before concat
        cleaned = [df.loc[:, ~df.columns.duplicated()] for df in all_canton]
        df_out = pd.concat(cleaned, ignore_index=True)
        out_path = os.path.join(OUTPUT_DIR, "canton_risk_group.csv")
        df_out.to_csv(out_path, index=False)
        print(f"canton_risk_group -> {out_path}  ({len(df_out)} rows, {df_out['year'].nunique()} years)")

    if all_ch_summary:
        cleaned_ch = [df.loc[:, ~df.columns.duplicated()] for df in all_ch_summary]
        df_out = pd.concat(cleaned_ch, ignore_index=True)
        out_path = os.path.join(OUTPUT_DIR, "switzerland_summary.csv")
        df_out.to_csv(out_path, index=False)
        print(f"switzerland_summary -> {out_path}  ({len(df_out)} rows, {df_out['year'].nunique()} years)")

    if not any([all_canton, all_ch_summary]):
        print("\nNo output tables produced. Check era filter or inspect schema_profile.csv for sheet structures.")


if __name__ == "__main__":
    main()
